---
title: "**Continuous & Ordinal**"
runtime: shiny
output: 
  html_document: 
    code_download: false
    toc: true
    toc_float: true
    theme: cerulean
    highlight: kate
mainfont: Arial
fontsize: 11pt
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DT)
library(plotly)


nparcomp_table <- function(x, group, df){



  if (!require("tidyverse")) install.packages("tidyverse")
  if (!require("gridExtra")) install.packages("gridExtra")
  if (!require("MCPAN")) install.packages("MCPAN")
  library(MCPAN)
  library(nparcomp)
  library(tidyverse)
  library(gridExtra)

  df <- df %>% rename(x=x, group=group)


  ss <- tapply(df$x, df$group, length)
 # print(ss)
  Mat <- contrMat(ss, type="GrandMean")
  wf3 <- mctp(as.numeric(x) ~ group, data=df, type="UserDefined",
              contrast.matrix=Mat, alternative="two.sided", info=FALSE,
              correlation=TRUE, asy.method="mult.t")

  wf4 <- wf3$Analysis  %>% mutate(Size=wf3$Data.Info$Size, group=wf3$Data.Info$Sample)
print(wf4)


  REF <- group

  ss <- wf4 %>%  dplyr::select(group, Size,  Estimator, Lower, Upper, p.Value) %>%
    mutate(p.Value=as.character(round(p.Value, digits = 2)),  Size_c=as.character(Size)) %>%
  add_row(group = REF, Size=NA, Estimator=NA, Lower=NA,  Upper=NA, p.Value= "P.val", Size_c="N" )  %>% mutate(group=as.factor(group)) %>%
   mutate(group= forcats::fct_relevel(group, REF, after = Inf)) %>% dplyr::select(-Size_c)
print(ss)
lastrownumber<- nrow(ss)

  return(ss[-lastrownumber,])
}


nparcomp <- function(x, group, df){



  if (!require("tidyverse")) install.packages("tidyverse")
  if (!require("gridExtra")) install.packages("gridExtra")
  if (!require("MCPAN")) install.packages("MCPAN")
  library(MCPAN)
  library(nparcomp)
  library(tidyverse)
  library(gridExtra)

  df <- df %>% rename(x=x, group=group)


  ss <- tapply(df$x, df$group, length)
 # print(ss)
  Mat <- contrMat(ss, type="GrandMean")
  wf3 <- mctp(as.numeric(x) ~ group, data=df, type="UserDefined",
              contrast.matrix=Mat, alternative="two.sided", info=FALSE,
              correlation=TRUE, asy.method="mult.t")

  wf4 <- wf3$Analysis  %>% mutate(Size=wf3$Data.Info$Size, group=wf3$Data.Info$Sample)
print(wf4)


  REF <- group

  ss <- wf4 %>%  dplyr::select(group, Size,  Estimator, Lower, Upper, p.Value) %>%
    mutate(p.Value=as.character(round(p.Value, digits = 2)),  Size_c=as.character(Size)) %>%
  add_row(group = REF, Size=NA, Estimator=NA, Lower=NA,  Upper=NA, p.Value= "P.val", Size_c="N" )  %>% mutate(group=as.factor(group)) %>%
   mutate(group= forcats::fct_relevel(group, REF, after = Inf))
print(ss)


  g1 <- ggplot(ss, aes(x = Estimator, xmin = as.numeric(Lower),
                       xmax = as.numeric(Upper), y = group)) + geom_point(aes(size=5),
                                                                           shape = 22, fill = "darkblue") + geom_errorbarh(height = 0.2) +
    geom_vline(xintercept = 0, linetype = "longdash", colour = "black") +
    #scale_x_continuous(trans = "log10", breaks = breaks) +
    #xlab("Odds Ratio (95%-KI)") +
    theme_classic(14) +
    theme(#axis.title.x = element_text(),
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(), legend.position = "none")+xlab("")

  title_text_size = 18
  table_text_size = 5

#  column_space = c(-0.5, -0.47, -0.45)
  column_space = c(-0.49, -0.47, -0.45)

    plot_opts = NULL; table_opts = NULL

  t1 <- ggplot(ss, aes(x = as.numeric(Estimator), y = group)) +
    scale_x_continuous(limits=c(-0.5, -0.45))+
    annotate("text", x = column_space[1], y = ss$group,
             label = ss[, 1], hjust = 0, size = table_text_size) +
    annotate("text", x = column_space[2], y = ss$group,
             label = ss[, 7], hjust = 1, size = table_text_size) +

    annotate("text", x = column_space[3], y =ss$group,
             label = ss[, 6], hjust = 1, size = table_text_size) +



    theme_classic(14) + theme(axis.title.x = element_text(colour = "white"),
                              axis.text.x = element_text(colour = "white"), axis.title.y = element_blank(),
                              axis.text.y = element_blank(), axis.ticks.y = element_blank(),
                              line = element_blank())

  g1 = g1 + plot_opts
  t1 = t1 + table_opts

out <- gridExtra::grid.arrange(t1, g1, ncol = 2, widths = c(1, 1.5)  )

#out <- subplot(t1, g1)
  return(out)
}

```


# **Data import**
```{r eruptions, echo=FALSE}


#dat_ex2 <- data.frame(Centers=factor(rep(letters[c(1,4,5,8,9,10, 14)], 3)), Age=rnorm(21, mean = 30))


dat_ex2 <- data.frame(Centers=factor(c(rep(letters[c(1,4,5,8,9,10, 14)], 10), 
                            
                            rep(letters[c(2, 7, 13)], 4)  , 
                            rep(letters[c(6, 12, 11)], 3) )
                          
                          ), 
           
          Age=c(rnorm(20, mean = 20), rnorm(13, mean = 10), rnorm(58, mean = 50) )
           
           )




  sidebarLayout(
            sidebarPanel(
                fileInput("inFIle2_", "Choose CSV File")
                ,
                tags$hr(),
                          ),
            mainPanel(
                tableOutput("data")
            )
        )

   dat2 <- reactive({
            # input$inFIle2_ will be NULL initially. After the user selects
            # and uploads a file, it will be a data frame with 'name',
            # 'size', 'type', and 'datapath' columns. The 'datapath'
            # column will contain the local filenames where the data can
            # be found.
            inFIle2_ <- input$inFIle2_

            if (is.null(inFIle2_))
                return(NULL)

            read.csv(inFIle2_$datapath,  row.names=FALSE)
        })





  dat2 <- reactive({
     inFIle2_ <- input$inFIle2_
    if(is.null(inFIle2_)){
      
   dat_ex2
      
    } else{
      
         read.csv(inFIle2_$datapath, stringsAsFactors = T) #%>% dplyr::select(1,2,4)
      
    }
      

    })


```


# **Data read and variable specification**
```{r output data, echo=FALSE}

renderPrint(str(dat2()))

  renderDataTable(dat2(), extensions = 'Buttons', 
                  options = list(dom = 'Bfrtip',
                  buttons = c('copy', 'csv', 'excel', 'pdf', 'print')), server = FALSE)
  


inputPanel(

#textInput("x", "name of g x", "Age"),
selectInput("a", "Name of outcome variable:", choices=names(dat2) ),
  
#textInput("y", "name variable y", "Centers"),

selectInput("b", "Name of grouping variable:", choices=names(dat2)),

)
  

a <- renderText({ input$a })
b <- renderText({ input$b })
  


  
 observeEvent(dat2(), {
                   updateSelectInput(session,
                                     "a",
                                     choices = names(dat2()), selected = "Age")
                   updateSelectInput(session,
                                     "b",
                                     choices = names(dat2()),  selected = "Centers")
                 })

 
 
```

# **Contrasts**
## **Simultaneous confidence intervals for contrasts of `r reactive(b())` means with GM for given data set**

```{r output_comparison, echo=FALSE}

table_nparcomp <- reactive({
    nparcomp_table(x=a(), group=b(), df=dat2())

})


  renderDataTable(table_nparcomp(), extensions = 'Buttons', 
                  options = list(dom = 'Bfrtip',
                  buttons = c('copy', 'csv', 'excel', 'pdf', 'print')), server = FALSE)
  


plot_nparcomp <- reactive({
    nparcomp(x=a(), group=b(), df=dat2())

  
  
})


 renderPlot(plot_nparcomp())




```

